---@class Buff
---@field public Name string
---@field public IsDebuff boolean
---@field public IsAbilityEffect boolean
---@field public IsBeforeAction boolean
---@field public Count number
---@field public RemainTime number
