---@class Skill
---@field public Name string
---@field public Type string
---@field public IsBlocked boolean
---@field public CoolDown number
---@field public OriginalSP number
---@field public SP number
---@field public Count number
