//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonSpiritsINFight.Assets {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("INFight.Res.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        public static string Home_PageName {
            get {
                return ResourceManager.GetString("Home_PageName", resourceCulture);
            }
        }
        
        public static string Party_PageName {
            get {
                return ResourceManager.GetString("Party_PageName", resourceCulture);
            }
        }
        
        public static string Battle_PageName {
            get {
                return ResourceManager.GetString("Battle_PageName", resourceCulture);
            }
        }
        
        public static string Explorer_PageName {
            get {
                return ResourceManager.GetString("Explorer_PageName", resourceCulture);
            }
        }
        
        public static string Synthesize_PageName {
            get {
                return ResourceManager.GetString("Synthesize_PageName", resourceCulture);
            }
        }
        
        public static string Training_PageName {
            get {
                return ResourceManager.GetString("Training_PageName", resourceCulture);
            }
        }
        
        public static string Setting_PageName {
            get {
                return ResourceManager.GetString("Setting_PageName", resourceCulture);
            }
        }
        
        public static string Type_Unknown {
            get {
                return ResourceManager.GetString("Type_Unknown", resourceCulture);
            }
        }
        
        public static string Type_Fire {
            get {
                return ResourceManager.GetString("Type_Fire", resourceCulture);
            }
        }
        
        public static string Type_Water {
            get {
                return ResourceManager.GetString("Type_Water", resourceCulture);
            }
        }
        
        public static string Type_Windy {
            get {
                return ResourceManager.GetString("Type_Windy", resourceCulture);
            }
        }
        
        public static string Type_Ground {
            get {
                return ResourceManager.GetString("Type_Ground", resourceCulture);
            }
        }
        
        public static string Type_Light {
            get {
                return ResourceManager.GetString("Type_Light", resourceCulture);
            }
        }
        
        public static string Type_Dark {
            get {
                return ResourceManager.GetString("Type_Dark", resourceCulture);
            }
        }
        
        public static string Type_Ether {
            get {
                return ResourceManager.GetString("Type_Ether", resourceCulture);
            }
        }
    }
}
